name: boozimba
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_custom_clippers: ^2.0.0
  get: ^4.3.8
  neon: ^0.1.0
  flutter_rating_bar: ^4.0.0
  circular_menu: 1.2.3
  bordered_text: ^2.0.0
  percent_indicator: ^3.0.1
  flutter_arc_speed_dial: ^2.0.0
  #smooth_star_rating: ^1.1.1
  flutter_svg: ^0.22.0
  stories_for_flutter: ^1.1.1
  google_fonts: ^2.1.0
  flutter_custom_dialog: ^1.2.0
  roller_list: ^1.0.2
  fab_circular_menu: ^1.0.0
  syncfusion_flutter_calendar: ^19.3.57
  syncfusion_flutter_datepicker: ^19.4.47
  outlined_text: ^1.0.1
  audioplayers: ^0.20.1
  vibration: ^1.7.3
  geolocator: ^8.0.5
  geocoding: ^2.0.2
  google_maps_flutter: ^2.1.1
  location: ^4.2.0
  flutter_staggered_grid_view: ^0.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/svgs/
    - assets/svgs/slot-icon/Ambiance/
    - assets/svgs/slot-icon/Drinks/
    - assets/svgs/slot-icon/Food/
    - assets/svgs/slot-icon/new/
    - assets/slotMachineSound.mp3  

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100
    - family: Segoe
      fonts:
        - asset: assets/fonts/Segoe UI.ttf
        - asset: assets/fonts/Segoe UI Bold.ttf
          weight: 700
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
